### ISSUE TITLE
Wrong github account ?

### ISSUE THREAD

**Issue by exadeci** [AndroidLibsCom/Android-Libs#19]
I logged in with my github account but it show a different user...
![capture d ecran 2015-01-14 a 15 48 40](https://cloud.githubusercontent.com/assets/1394130/5740630/587984b8-9c05-11e4-86cf-94e9eb2cb0be.png)

**Comment by Cyruxx** [comment]
Yes this is happening because of incorrect validation at sign in. Might be that the GitHub API didn't return a email address for your account.
